/**
 * ============================================================
 * ALAMTOLOGI-QURANIC SCIENCE
 * ============================================================
 * Module      : Quran Surah Names
 * Platform    : Backend (TypeScript)
 * ALAMTOLOGI  : Kernel v1.7.0
 * Founder     : Masa Bayu
 * Created     : 2026-05-30
 * ============================================================
 * CONSTITUTIONAL DECLARATION:
 * This module operates under the Alamtologi Constitutional
 * Framework. All actions are governed by Alamtologi. Knowledge
 * belongs to no human. It flows like water to all.
 * ============================================================
 */

/** Normalized surah name → number (1–114). Keys: lowercase, hyphens. */
export const SURAH_NAME_TO_NUMBER: Record<string, number> = {
  'al-fatihah':           1,
  'fatihah':              1,
  'al-fatiha':            1,
  'fatiha':               1,
  'al-baqarah':           2,
  'baqarah':              2,
  'al-baqara':            2,
  'ali-imran':            3,
  'al-imran':             3,
  'an-nisa':              4,
  'an-nisaa':             4,
  'al-maidah':            5,
  'al-ma\'idah':          5,
  'al-anam':              6,
  'al-an\'am':            6,
  'al-araf':              7,
  'al-a\'raf':            7,
  'al-anfal':             8,
  'at-tawbah':            9,
  'yunus':                10,
  'hud':                  11,
  'yusuf':                12,
  'ar-rad':               13,
  'ibrahim':              14,
  'al-hijr':              15,
  'an-nahl':              16,
  'al-isra':              17,
  'al-kahf':              18,
  'maryam':               19,
  'ta-ha':                20,
  'ta-hah':               20,
  'al-anbya':             21,
  'al-anbiya':            21,
  'al-hajj':              22,
  'al-muminun':           23,
  'an-nur':               24,
  'al-furqan':            25,
  'ash-shuara':           26,
  'an-naml':              27,
  'al-qasas':             28,
  'al-ankabut':           29,
  'ar-rum':               30,
  'luqman':               31,
  'as-sajdah':            32,
  'al-ahzab':             33,
  'saba':                 34,
  'fatir':                35,
  'ya-sin':               36,
  'yasin':                36,
  'as-saffat':            37,
  'sad':                  38,
  'az-zumar':             39,
  'ghafir':               40,
  'fussilat':             41,
  'ash-shuraa':           42,
  'az-zukhruf':           43,
  'ad-dukhan':            44,
  'al-jathiyah':          45,
  'al-ahqaf':             46,
  'muhammad':             47,
  'al-fath':              48,
  'al-hujurat':           49,
  'qaf':                  50,
  'adh-dhariyat':         51,
  'at-tur':               52,
  'an-najm':              53,
  'al-qamar':             54,
  'ar-rahman':            55,
  'al-waqiah':            56,
  'al-hadid':             57,
  'al-mujadila':          58,
  'al-hashr':             59,
  'al-mumtahanah':        60,
  'as-saf':               61,
  'al-jumuah':            62,
  'al-munafiqun':         63,
  'at-taghabun':          64,
  'at-talaq':             65,
  'at-tahrim':            66,
  'al-mulk':              67,
  'al-qalam':             68,
  'al-haqqah':            69,
  'al-maarij':            70,
  'nuh':                  71,
  'al-jinn':              72,
  'al-muzzammil':         73,
  'al-muddaththir':       74,
  'al-qiyamah':           75,
  'al-insan':             76,
  'al-mursalat':          77,
  'an-naba':              78,
  'an-naziat':            79,
  'abasa':                80,
  'at-takwir':            81,
  'al-infitar':           82,
  'al-mutaffifin':        83,
  'al-inshiqaq':          84,
  'al-buruj':             85,
  'at-tariq':             86,
  'al-ala':               87,
  'al-ghashiyah':         88,
  'al-fajr':              89,
  'al-balad':             90,
  'ash-shams':            91,
  'al-layl':              92,
  'ad-duhaa':             93,
  'ash-sharh':            94,
  'at-tin':               95,
  'al-alaq':              96,
  'al-qadr':              97,
  'al-bayyinah':          98,
  'az-zalzalah':          99,
  'al-adiyat':            100,
  'al-qariah':            101,
  'at-takathur':          102,
  'al-asr':               103,
  'al-humazah':           104,
  'al-fil':               105,
  'quraysh':              106,
  'al-maun':              107,
  'al-kawthar':           108,
  'al-kafirun':           109,
  'an-nasr':              110,
  'al-masad':             111,
  'al-ikhlas':            112,
  'al-falaq':             113,
  'an-nas':               114,
};

export const SURAH_NUMBER_TO_NAME: Record<number, string> = {
  1:  'Al-Fatihah',
  2:  'Al-Baqarah',
  3:  'Ali Imran',
  4:  'An-Nisa',
  5:  'Al-Maidah',
  6:  'Al-Anam',
  7:  'Al-Araf',
  8:  'Al-Anfal',
  9:  'At-Tawbah',
  10: 'Yunus',
  11: 'Hud',
  12: 'Yusuf',
  13: 'Ar-Rad',
  14: 'Ibrahim',
  15: 'Al-Hijr',
  16: 'An-Nahl',
  17: 'Al-Isra',
  18: 'Al-Kahf',
  19: 'Maryam',
  20: 'Ta-Ha',
  36: 'Ya-Sin',
  55: 'Ar-Rahman',
  67: 'Al-Mulk',
  112: 'Al-Ikhlas',
  113: 'Al-Falaq',
  114: 'An-Nas',
};
