/**
 * ============================================================
 * ALAMTOLOGI-QURANIC SCIENCE
 * ============================================================
 * Module      : ADAM Document Export Service
 * Platform    : Backend (TypeScript)
 * QXK24       : Kernel v1.7.0
 * Founder     : Masa Bayu
 * Created     : 2026-06-11
 * ============================================================
 * CONSTITUTIONAL DECLARATION:
 * This module operates under the Alamtologi Constitutional
 * Framework. All actions are governed by QXK24. Knowledge
 * belongs to no human. It flows like water to all.
 * ============================================================
 */

import PDFDocument from 'pdfkit';
import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import {
  parseInlineBoldSegments,
  parseMarkdownExportBlocks,
  type ExportBlock,
} from './adam-markdown-export-blocks';

export type AdamExportFormat = 'pdf' | 'docx';

export interface CompileAdamDocumentInput {
  content: string;
  format:  AdamExportFormat;
  title?:  string;
  author?: string;
}

export interface CompiledAdamDocument {
  buffer:   Buffer;
  mimeType: string;
  filename: string;
}

function safeFilename(title: string): string {
  return title
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 64) || 'adam-lesson';
}

function docxParagraphFromText(text: string, opts?: { heading?: typeof HeadingLevel[keyof typeof HeadingLevel] }): Paragraph {
  const runs = parseInlineBoldSegments(text).map(
    (seg) => new TextRun({ text: seg.text, bold: seg.bold }),
  );
  return new Paragraph({
    heading: opts?.heading,
    children: runs.length ? runs : [new TextRun(text)],
    spacing: { after: 120 },
  });
}

function docxTableBlock(headers: string[], rows: string[][]): Table {
  const headerRow = new TableRow({
    children: headers.map(
      (h) => new TableCell({
        children: [docxParagraphFromText(h)],
        shading:  { fill: '615CED' },
      }),
    ),
  });

  const bodyRows = rows.map(
    (row) => new TableRow({
      children: row.map(
        (cell) => new TableCell({
          children: [docxParagraphFromText(cell || '')],
        }),
      ),
    }),
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows:  [headerRow, ...bodyRows],
  });
}

async function buildDocx(input: CompileAdamDocumentInput): Promise<Buffer> {
  const title = input.title?.trim() || 'ADAM — Lesson note';
  const blocks = parseMarkdownExportBlocks(input.content);
  const children: Array<Paragraph | Table> = [
    new Paragraph({
      text:    title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }),
  ];

  if (input.author?.trim()) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Prepared for ${input.author.trim()}`, italics: true, size: 20 })],
        spacing:  { after: 160 },
      }),
    );
  }

  for (const block of blocks) {
    children.push(...blockToDocxElements(block));
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'Generated by ADAM · Alamtologi', size: 18, color: '666666' })],
      spacing:  { before: 240 },
    }),
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return Packer.toBuffer(doc);
}

function blockToDocxElements(block: ExportBlock): Array<Paragraph | Table> {
  switch (block.type) {
    case 'heading':
      return [docxParagraphFromText(block.text, {
        heading: block.level <= 1 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
      })];
    case 'table':
      return [docxTableBlock(block.headers, block.rows)];
    case 'answer':
      return [
        new Paragraph({
          children: [
            new TextRun({ text: block.text, font: 'Courier New', size: 22 }),
          ],
          spacing: { before: 120, after: 120 },
          shading: { fill: 'F4F3FF' },
        }),
      ];
    case 'paragraph':
    default:
      return [docxParagraphFromText(block.text)];
  }
}

async function buildPdf(input: CompileAdamDocumentInput): Promise<Buffer> {
  const title = input.title?.trim() || 'ADAM — Lesson note';
  const blocks = parseMarkdownExportBlocks(input.content);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (c) => chunks.push(c as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(18).fillColor('#1e1b4b').text(title);
    doc.moveDown(0.4);

    if (input.author?.trim()) {
      doc.font('Helvetica-Oblique').fontSize(10).fillColor('#555555')
        .text(`Prepared for ${input.author.trim()}`);
      doc.moveDown(0.6);
    }

    doc.fillColor('#111111');

    for (const block of blocks) {
      renderPdfBlock(doc, block);
    }

    doc.moveDown(1);
    doc.font('Helvetica').fontSize(9).fillColor('#666666')
      .text('Generated by ADAM · Alamtologi', { align: 'left' });

    doc.end();
  });
}

function ensurePdfSpace(doc: PDFKit.PDFDocument, needed: number): void {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + needed > bottom) {
    doc.addPage();
  }
}

function renderPdfBlock(doc: PDFKit.PDFDocument, block: ExportBlock): void {
  const left = doc.page.margins.left;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.x = left;

  switch (block.type) {
    case 'heading':
      ensurePdfSpace(doc, 28);
      doc.moveDown(0.45);
      doc.x = left;
      doc.font('Helvetica-Bold').fontSize(block.level <= 1 ? 14 : 12).fillColor('#2c2c54')
        .text(stripBoldMarkers(block.text), left, doc.y, { width: pageWidth, lineGap: 2 });
      doc.x = left;
      doc.moveDown(0.35);
      break;

    case 'paragraph':
      ensurePdfSpace(doc, 20);
      renderPdfInlineText(doc, block.text, pageWidth);
      doc.x = left;
      doc.moveDown(0.4);
      break;

    case 'answer': {
      doc.moveDown(0.15);
      const pad = 8;
      doc.font('Courier').fontSize(10);
      const textHeight = doc.heightOfString(block.text, { width: pageWidth - pad * 2, lineGap: 2 });
      const boxHeight = Math.max(28, textHeight + pad * 2);
      ensurePdfSpace(doc, boxHeight + 8);
      const boxY = doc.y;
      doc.rect(left, boxY, pageWidth, boxHeight).fill('#f4f3ff');
      doc.fillColor('#4338ca')
        .text(block.text, left + pad, boxY + pad, {
          width:   pageWidth - pad * 2,
          lineGap: 2,
        });
      doc.fillColor('#111111');
      doc.y = boxY + boxHeight + 8;
      doc.x = left;
      break;
    }

    case 'table':
      renderPdfTable(doc, block.headers, block.rows, pageWidth);
      doc.x = left;
      doc.moveDown(0.5);
      break;

    default:
      break;
  }
}

function stripBoldMarkers(text: string): string {
  return text.replace(/\*\*([^*]+)\*\*/g, '$1');
}

/**
 * PDFKit `continued: true` across wrapped lines often leaves `doc.y` wrong,
 * so the next block overlaps. Render each visual line as its own text run.
 */
function renderPdfInlineText(doc: PDFKit.PDFDocument, text: string, width: number): void {
  const left = doc.page.margins.left;
  const lines = text.split('\n');

  for (let li = 0; li < lines.length; li++) {
    const line = lines[li] ?? '';
    doc.x = left;
    const segments = parseInlineBoldSegments(line);

    if (segments.length === 0 || (segments.length === 1 && !segments[0]!.text)) {
      doc.moveDown(0.35);
      continue;
    }

    ensurePdfSpace(doc, 16);

    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i]!;
      const isLast = i === segments.length - 1;
      doc.font(seg.bold ? 'Helvetica-Bold' : 'Helvetica')
        .fontSize(11)
        .fillColor('#111111')
        .text(seg.text, {
          continued: isLast ? false : true,
          width,
          lineGap:   3,
          align:     'left',
        });
    }

    doc.x = left;
    if (li < lines.length - 1) {
      // Explicit gap between hard-wrapped markdown lines (e.g. list items).
      doc.moveDown(0.15);
    }
  }

  doc.x = left;
}

function renderPdfTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  pageWidth: number,
): void {
  const cols = Math.max(headers.length, ...rows.map((r) => r.length), 1);
  const colWidth = pageWidth / cols;
  const rowHeight = 22;
  let y = doc.y;

  doc.font('Helvetica-Bold').fontSize(9);
  for (let c = 0; c < cols; c++) {
    const x = doc.page.margins.left + c * colWidth;
    doc.rect(x, y, colWidth, rowHeight).fillAndStroke('#615ced', '#ffffff');
    doc.fillColor('#ffffff').text(headers[c] ?? '', x + 4, y + 6, {
      width: colWidth - 8,
      align: 'center',
    });
  }
  y += rowHeight;

  doc.font('Helvetica').fontSize(10).fillColor('#1e1b4b');
  for (const row of rows) {
    for (let c = 0; c < cols; c++) {
      const x = doc.page.margins.left + c * colWidth;
      doc.rect(x, y, colWidth, rowHeight).stroke('#dddddd');
      doc.text(row[c] ?? '', x + 4, y + 6, { width: colWidth - 8, align: 'center' });
    }
    y += rowHeight;
  }

  doc.y = y;
}

export async function compileAdamDocument(
  input: CompileAdamDocumentInput,
): Promise<CompiledAdamDocument> {
  const title = input.title?.trim() || 'ADAM — Lesson note';
  const base = safeFilename(title);
  const stamp = new Date().toISOString().slice(0, 10);

  if (input.format === 'docx') {
    const buffer = await buildDocx(input);
    return {
      buffer,
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      filename: `${base}-${stamp}.docx`,
    };
  }

  const buffer = await buildPdf(input);
  return {
    buffer,
    mimeType: 'application/pdf',
    filename: `${base}-${stamp}.pdf`,
  };
}
